# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{elastic_searchable}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Sonnek"]
  s.date = %q{2011-03-04}
  s.description = %q{integrate the elastic search engine with rails}
  s.email = %q{ryan@codecrate.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "elastic_searchable.gemspec",
    "lib/elastic_searchable.rb",
    "lib/elastic_searchable/active_record.rb",
    "lib/elastic_searchable/callbacks.rb",
    "lib/elastic_searchable/index.rb",
    "lib/elastic_searchable/queries.rb",
    "test/database.yml",
    "test/helper.rb",
    "test/test_elastic_searchable.rb"
  ]
  s.homepage = %q{http://github.com/wireframe/elastic_searchable}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{elastic search for activerecord}
  s.test_files = [
    "test/helper.rb",
    "test/test_elastic_searchable.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 2.3.5"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.6.0"])
      s.add_runtime_dependency(%q<backgrounded>, ["~> 0.7.0"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 2.3.15"])
      s.add_runtime_dependency(%q<larsklevan-after_commit>, ["~> 1.0.5"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
    else
      s.add_dependency(%q<activerecord>, ["~> 2.3.5"])
      s.add_dependency(%q<httparty>, ["~> 0.6.0"])
      s.add_dependency(%q<backgrounded>, ["~> 0.7.0"])
      s.add_dependency(%q<will_paginate>, ["~> 2.3.15"])
      s.add_dependency(%q<larsklevan-after_commit>, ["~> 1.0.5"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 2.3.5"])
    s.add_dependency(%q<httparty>, ["~> 0.6.0"])
    s.add_dependency(%q<backgrounded>, ["~> 0.7.0"])
    s.add_dependency(%q<will_paginate>, ["~> 2.3.15"])
    s.add_dependency(%q<larsklevan-after_commit>, ["~> 1.0.5"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, ["~> 1.3.2"])
  end
end

